//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefuelingDriverJournal
    {
        public System.Guid ID { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Cost { get; set; }
        public string Comment { get; set; }
        public System.Guid VehicleID { get; set; }
        public int TypeOfCostID { get; set; }
    
        public virtual TypeOfCost TypeOfCost { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
