//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportDriverJournal
    {
        public System.Guid ID { get; set; }
        public System.DateTime Date { get; set; }
        public int Milage { get; set; }
        public decimal FuelAmount { get; set; }
        public decimal PricePerUnit { get; set; }
        public decimal TotalPrice { get; set; }
        public System.Guid ChauffeurID { get; set; }
        public System.Guid VehicleID { get; set; }
        public int FuelTypeID { get; set; }
    
        public virtual FuelType FuelType { get; set; }
        public virtual User User { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
