//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicle()
        {
            this.RefuelingDriverJournal = new HashSet<RefuelingDriverJournal>();
            this.ReportDriverJournal = new HashSet<ReportDriverJournal>();
        }
    
        public System.Guid ID { get; set; }
        public string RegNo { get; set; }
        public int OriginalMileage { get; set; }
        public string Desription { get; set; }
        public Nullable<int> ColorID { get; set; }
        public int VehicleTypeID { get; set; }
        public Nullable<int> ModelYearID { get; set; }
        public int FuelTypeID { get; set; }
    
        public virtual Color Color { get; set; }
        public virtual FuelType FuelType { get; set; }
        public virtual ModelYear ModelYear { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RefuelingDriverJournal> RefuelingDriverJournal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportDriverJournal> ReportDriverJournal { get; set; }
        public virtual VehicleType VehicleType { get; set; }
    }
}
